example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist
from wishlist.views import show_wishlist_ajax
from wishlist.views import show_xml
from wishlist.views import show_json
from wishlist.views import show_json_by_id
from wishlist.views import show_xml_by_id
from wishlist.views import register
from wishlist.views import login_user
from wishlist.views import logout_user
from wishlist.views import create

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
    path('ajax/submit/', create, name='create'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render, redirect
from wishlist.models import BarangWishlist
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http.response import JsonResponse
from django.contrib.auth.models import User
import datetime

# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
    'list_barang': data_barang_wishlist,
    'nama': 'Muhammad Hilman Al Ayubi',
    }
    return render(request, "wishlist.html", context)

@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
    'nama': 'Muhammad Hilman Al Ayubi',
    }
    return render(request, "wishlist_ajax.html", context)

@login_required(login_url='/wishlist/login/')
def create(request):
    if request.method == 'POST':
        nama_barang = request.POST.get('nama_barang')
        harga_barang = request.POST.get('harga_barang')
        deskripsi = request.POST.get('deskripsi')
        item = BarangWishlist(nama_barang=nama_barang, harga_barang=harga_barang, deskripsi=deskripsi)
        item.save()
        return JsonResponse({"instance": "Proyek Dibuat"}, status=200)
    
    return render(request, "create.html")

def show_xml(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data_barang_wishlist), content_type="application/xml")

def show_json(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data_barang_wishlist), content_type="application/json")

def show_xml_by_id(request, id):
    data_barang_wishlist_by_id = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data_barang_wishlist_by_id), content_type="application/xml")

def show_json_by_id(request, id):
    data_barang_wishlist_by_id = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data_barang_wishlist_by_id), content_type="application/json")

def register(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        form = UserCreationForm(request.POST)
        if username and password:
            try:
                acc = User.objects.create(username=username)
                if acc:
                    acc.set_password(password)
                    acc.save()
                    messages.success(request, 'Akun telah berhasil dibuat!')
                    return redirect('wishlist:login')
                else:
                    messages.success(request, 'Terjadi masalah!')
            except:
                messages.success(request, 'Username sudah pernah digunakan!')
        else:
            messages.success(request, 'Tidak boleh kosong!')

    
    context = {}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) 
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist_ajax")) 
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

@login_required(login_url='/wishlist/login/')
def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    return response

example_app/templates/index.html
<!-- prettier-ignore -->
{% extends 'base.html' %} 
{% load static %} 
{% block meta %}
<title>Hello, world!</title>
<!-- prettier-ignore -->
{% endblock meta %} 
{% block content %}
<h1 class="text-red-500">Hello, world!</h1>
<h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!-- prettier-ignore -->
{% load tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% tailwind_css %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
      crossorigin="anonymous"
    />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- prettier-ignore -->
    {% block meta %} 
    {% endblock meta %}
  </head>

  <body>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
      integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js"
      integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk"
      crossorigin="anonymous"
    ></script>
    <!-- prettier-ignore -->
    {% block content %} 
    {% endblock content %}
  </body>
</html>

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>

wishlist/templates/create.html
{% extends 'base.html' %}
<!-- prettier-ignore -->
{% block meta %}
<title>Create Wishlist</title>
<script>
  // function loadData() {
  //   $.get("{% url 'wishlist:show_json' %}", function (data) {
  //     show(data);
  //   });
  // }

  $(document).on("submit", "#buatproject", function (e) {
    e.preventDefault();
    $.ajax({
      type: "POST",
      url: "{% url 'wishlist:create' %}",
      data: {
        nama_barang: $("#nama_barang").val(),
        harga_barang: $("#harga_barang").val(),
        deskripsi: $("#deskripsi").val(),
        csrfmiddlewaretoken: "{{ csrf_token }}",
      },
      dataType: "json",
      success: function () {
        alert("Proyek Berhasil Ditambahkan!");
      },
    });
  });

  // $(document).ready(function () {
  //   $("#button").click(function (e) {
  //     console.log("click");
  //     e.preventDefault();
  //     console.log(document.querySelector("#nama_barang").value);
  //     console.log(document.querySelector("#harga_barang").value);
  //     console.log(document.querySelector("#deskripsi").value);
  //     $.post("{% url 'wishlist:create' %}", {
  //       nama_barang: document.querySelector("#nama_barang").value,
  //       harga_barang: document.querySelector("#harga_barang").value,
  //       deskripsi: document.querySelector("#deskripsi").value,
  //       csrfmiddlewaretoken: "{{ csrf_token }}",
  //       function(data) {
  //         alert("Proyek Berhasil Ditambahkan!");
  //       },
  //       json,
  //     });
  //   });
  // });
</script>
{% endblock meta %}
<!-- prettier-ignore -->
{% block content %}

<div class="bg-[#BEBEBE] w-full min-h-screen px-10 py-10 space-y-5">
  <form action="" id="buatproject">
    {% csrf_token %}
    <div class="w-full">
      <p class="">Nama</p>
      <input
        type="text"
        name="nama_barang"
        id="nama_barang"
        class="form-control rounded-md border border-gray-400 w-full"
        placeholder="Nama"
      />
    </div>
    <div class="w-full">
      <p class="">Harga</p>
      <input
        type="number"
        name="harga_barang"
        id="harga_barang"
        class="form-control rounded-md border border-gray-400 w-full"
        placeholder="Harga"
      />
    </div>
    <div class="w-full">
      <p class="">Deskripsi</p>
      <input
        type="text"
        name="deskripsi"
        id="deskripsi"
        class="form-control rounded-md border border-gray-400 w-full"
        placeholder="Deskripsi"
      />
    </div>
    <div class="w-full flex justify-end">
      <button
        class="py-1 md:px-8 px-2 rounded-lg cursor-pointer bg-[#FF9933] text-white"
        id="button"
        type="submit"
      >
        Tambah
      </button>
    </div>
  </form>
</div>

{% endblock content %}

wishlist/templates/login.html
{% extends 'base.html' %}
<!-- prettier-ignore -->
{% block meta %}
<title>Login</title>
{% endblock meta %}
<!-- prettier-ignore -->
{% block content %}

<div class="w-full min-h-screen bg-[#BEBEBE] flex items-center justify-center">
  <div class="w-[250px] h-[400px] sm:w-[400px] relative">
    <div class="w-full h-full bg-white absolute top-0 z-10 rounded-lg">
      <div
        class="w-full h-full sm:px-16 px-5 flex flex-col items-center relative"
      >
        <form method="POST" action="" class="w-full flex flex-col items-center">
          {% csrf_token %}
          <p class="font-bold text-4xl text-[#FF7F00] mt-5">LOGIN</p>
          <div class="space-y-5 w-full">
            <div class="w-full">
              <p class="text-sm">Username</p>
              <input
                type="text"
                name="username"
                class="form-control rounded-md border border-gray-400 w-full"
                placeholder="Enter Your Username here"
              />
            </div>
            <div>
              <p class="text-sm">Password</p>
              <input
                type="password"
                name="password"
                class="form-control rounded-md border border-gray-400 w-full"
                placeholder="Enter Your Password here"
              />
            </div>
          </div>
          <input
            class="mt-10 py-1 px-8 rounded-lg cursor-pointer bg-[#FF9933] text-white"
            type="submit"
            value="Login"
          />
        </form>
        {% if messages %}
        <div class="w-full flex flex-col items-center justify-center h-fit">
          {% for message in messages %}
          <p class="text-xs">{{ message }}</p>
          {% endfor %}
        </div>
        {% endif %}
        <div class="absolute right-0 bottom-0">
          <p class="text-sm">
            Belum punya akun?
            <a
              href="{% url 'wishlist:register' %}"
              class="text-[#FF7F00] underline"
              >Buat Akun</a
            >
          </p>
        </div>
      </div>
    </div>
    <div
      class="w-full h-full bg-[#D9D9D9] translate-x-3 translate-y-3 rounded-lg"
    ></div>
  </div>
</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}
<!-- prettier-ignore -->
{% block meta %}
<title>Login</title>
{% endblock meta %}
<!-- prettier-ignore -->
{% block content %}

<div class="w-full min-h-screen bg-[#BEBEBE] flex items-center justify-center">
  <div class="w-[250px] h-[400px] sm:w-[400px] relative">
    <div class="w-full h-full bg-white absolute top-0 z-10 rounded-lg">
      <div
        class="w-full h-full sm:px-16 px-5 flex flex-col items-center relative"
      >
        <form method="POST" action="" class="w-full flex flex-col items-center">
          {% csrf_token %}
          <p class="font-bold text-4xl text-[#FF7F00] my-10">Register</p>
          <div class="space-y-5 w-full">
            <div class="w-full">
              <p class="text-sm">Username</p>
              <input
                type="text"
                name="username"
                class="form-control rounded-md border border-gray-400 w-full"
                placeholder="Enter Your Username here"
              />
            </div>
            <div>
              <p class="text-sm">Password</p>
              <input
                type="password"
                name="password"
                class="form-control rounded-md border border-gray-400 w-full"
                placeholder="Enter Your Password here"
              />
            </div>
          </div>
          <input
            class="mt-10 py-1 px-8 rounded-lg cursor-pointer bg-[#FF9933] text-white"
            type="submit"
            value="Daftar"
          />
          {% if messages %}
          <ul>
            {% for message in messages %}
            <li class="text-xs mt-2">{{ message }}</li>
            {% endfor %}
          </ul>
          {% endif %}
        </form>
      </div>
    </div>
    <div
      class="w-full h-full bg-[#D9D9D9] translate-x-3 translate-y-3 rounded-lg"
    ></div>
  </div>
</div>

{% endblock content %}

wishlist/templates/wishlist.html
<!-- prettier-ignore -->
{% extends 'base.html' %} 

{% load static %}
<!-- prettier-ignore -->
{% block content %}

<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">{{nama}}</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Dropdown link
          </a>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="{% url 'wishlist:logout' %}"
                >Logout</a
              >
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

<table border="1" class="table table-bordered">
  <tr>
    <th>Nama Barang</th>
    <th>Harga Barang</th>
    <th>Deskripsi</th>
  </tr>
  {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
  <!-- prettier-ignore -->
  {% for barang in list_barang %}
  <tr>
    <th>{{barang.nama_barang}}</th>
    <th>{{barang.harga_barang}}</th>
    <th>{{barang.deskripsi}}</th>
  </tr>
  {% endfor %}
</table>

{% endblock content %}

wishlist/templates/wishlist_ajax.html
<!-- prettier-ignore -->
{% extends 'base.html' %}

<!-- prettier-ignore -->
{% block meta %}
<title>Wishlist Ajax</title>
<script>
  let tab;
  function show(data) {
    tab = `<tr>
            <th>Nama Barang</th>
            <th>Harga Barang</th>
            <th>Deskripsi</th>
         </tr>`;

    for (let r of data) {
      tab += `<tr> 
    <td>${r.fields.nama_barang} </td>
    <td>${r.fields.harga_barang}</td>
    <td>${r.fields.deskripsi}</td> 
</tr>`;
    }

    document.getElementById("table").innerHTML = tab;
  }

  function loadData() {
    $.get("{% url 'wishlist:show_json' %}", function (data) {
      show(data);
      console.log(data);
    });
  }

  $(document).ready(function () {
    loadData();
    $("#button").click(function () {
      console.log("clicked");
      loadData();
    });
  });

  $(document).on("submit", "#buatproject", function (e) {
    e.preventDefault();
    $.ajax({
      type: "POST",
      url: "{% url 'wishlist:create' %}",
      data: {
        nama_barang: $("#nama_barang").val(),
        harga_barang: $("#harga_barang").val(),
        deskripsi: $("#deskripsi").val(),
        csrfmiddlewaretoken: "{{ csrf_token }}",
      },
      dataType: "json",
      success: function () {
        alert("Proyek Berhasil Ditambahkan!");
        loadData();
      },
    });
  });

  function clickCounter() {
    if (typeof Storage !== "undefined") {
      if (sessionStorage.clickcount) {
        sessionStorage.clickcount = Number(sessionStorage.clickcount) + 1;
      } else {
        sessionStorage.clickcount = 1;
      }
      document.getElementById("result").innerHTML =
        "Counter: " + sessionStorage.clickcount;
    } else {
      document.getElementById("result").innerHTML =
        "Sorry, your browser does not support web storage...";
    }
  }
  function clickCounter1() {
    if (typeof Storage !== "undefined") {
      if (localStorage.clickcount) {
        localStorage.clickcount = Number(localStorage.clickcount) + 1;
      } else {
        localStorage.clickcount = 1;
      }
      document.getElementById("result1").innerHTML =
        "Counter: " + localStorage.clickcount;
    } else {
      document.getElementById("result1").innerHTML =
        "Sorry, your browser does not support web storage...";
    }
  }
</script>
{% endblock meta %}
<!-- prettier-ignore -->
{% block content %}

<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">{{nama}}</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <button id="button" class="nav-link">Load Data</button>
        </li>
        <li class="nav-item">
          <button
            type="button"
            class="nav-link"
            data-bs-toggle="modal"
            data-bs-target="#exampleModal"
          >
            Tambah Data
          </button>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'wishlist:logout' %}">Logout</a>
        </li>
        <li class="nav-item flex items-center gap-2">
          <button onclick="clickCounter()" type="button">
            Click me! (sessionStorage)
          </button>
          <div id="result" class="mr-2"></div>
        </li>
        <li class="nav-item flex items-center gap-2">
          <button onclick="clickCounter1()" type="button">
            Click me! (localStorage)
          </button>
          <div id="result1"></div>
        </li>
      </ul>
    </div>
  </div>
</nav>

<!-- Modal -->
<div
  class="modal fade"
  id="exampleModal"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Tambah Wishlist</h1>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <form action="" id="buatproject">
        {% csrf_token %}
        <div class="modal-body space-y-5">
          <div class="w-full">
            <p class="">Nama</p>
            <input
              type="text"
              name="nama_barang"
              id="nama_barang"
              class="form-control rounded-md border border-gray-400 w-full"
              placeholder="Nama"
            />
          </div>
          <div class="w-full">
            <p class="">Harga</p>
            <input
              type="number"
              name="harga_barang"
              id="harga_barang"
              class="form-control rounded-md border border-gray-400 w-full"
              placeholder="Harga"
            />
          </div>
          <div class="w-full">
            <p class="">Deskripsi</p>
            <input
              type="text"
              name="deskripsi"
              id="deskripsi"
              class="form-control rounded-md border border-gray-400 w-full"
              placeholder="Deskripsi"
            />
          </div>
        </div>
        <div class="modal-footer">
          <button
            type="button"
            class="btn btn-secondary"
            data-bs-dismiss="modal"
          >
            Close
          </button>
          <button
            type="submit"
            class="btn btn-primary"
            id="button"
            data-bs-dismiss="modal"
          >
            Post
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

<table border="1" class="table table-bordered" id="table"></table>

{% endblock content %}